# Generated by Django 4.2.6 on 2023-10-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postunlike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postunlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='unlikes',
        ),
        migrations.DeleteModel(
            name='CommentUnlike',
        ),
        migrations.DeleteModel(
            name='PostUnlike',
        ),
    ]
