# Generated by Django 4.2.6 on 2023-11-06 16:42

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_postunlike_post_remove_postunlike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=api.models.user_directory_path_post, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
